name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *" 

  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (create a personal access token with necessary scopes)
          token: ${{ secrets.METRICS_TOKEN }}
